spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/securityjwt
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace


# HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
# secret ?? ?? ???? Base64? ???? ?? ????(?? ???? ???? ?? ??)
# echo 'ThisIsSecretKeyForSpringSecurityAndJWT-practiceProject' | base64
jwt:
  secret: VGhpc0lzU2VjcmV0S2V5Rm9yU3ByaW5nU2VjdXJpdHlBbmRKV1QtcHJhY3RpY2VQcm9qZWN0Cg==
